import { promises as fsp } from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import type { SslCert } from '@/types';

/**
 * NginxManager — generates per-domain SSL fragments + the http redirect include
 * for qtechvending, then (re)applies them to the live nginx config using a safe
 * backup → `nginx -t` → reload → rollback workflow.
 *
 * Security model (see architecture §1.4 / risk R1–R4):
 *  - `NGINX_BIN` / `APP_UPSTREAM` / paths come from env, never from user input.
 *  - nginx is invoked via `execFileSync(bin, [args])` — arguments are an array,
 *    so there is NO shell interpolation / command injection surface.
 *  - Fragment file names are derived from `sanitizeDomain(domain)` (only
 *    [a-zA-Z0-9.-] survive) and written with `fs` (never via shell).
 *  - `certPath`/`keyPath` are strictly validated (absolute, no whitespace/
 *    quotes/newlines, no "..") before being emitted into a fragment, preventing
 *    nginx-config injection. We do NOT verify the files exist (PRD §6 boundary) —
 *    missing files are surfaced by `nginx -t`.
 */

const NGINX_BIN = process.env.NGINX_BIN || '/usr/sbin/nginx';
const APP_UPSTREAM = process.env.APP_UPSTREAM || 'http://127.0.0.1:3000';
const CONF_DIR = process.env.NGINX_CONF_DIR || '/etc/nginx/conf.d';
const MAIN_CONF = process.env.NGINX_MAIN_CONF || path.join(CONF_DIR, 'qtechvending.conf');

const SSL_FRAGMENT_PREFIX = 'qtechvending-ssl-';
const SSL_FRAGMENT_SUFFIX = '.conf';
const HTTP_INC_NAME = 'qtechvending-http.inc';

const SSL_INCLUDE_DIRECTIVE = `include ${CONF_DIR}/${SSL_FRAGMENT_PREFIX}*.conf;`;
const HTTP_INCLUDE_DIRECTIVE = `include ${CONF_DIR}/${HTTP_INC_NAME};`;

const DOMAIN_RE = /^[a-zA-Z0-9.-]+$/;
const SAFE_PATH_RE = /^\/[^\s'"\n\r]*$/;

/** Error type carrying a stable `code` used by callers / API responses. */
export class NginxError extends Error {
  code: string;
  constructor(code: string, message: string) {
    super(message);
    this.name = 'NginxError';
    this.code = code;
  }
}

/** Replace any unsafe character in a domain with "_" so it is safe for a file name. */
export function sanitizeDomain(domain: string): string {
  return (domain || '').replace(/[^a-zA-Z0-9.-]/g, '_');
}

/** Throw a NginxError if a domain is not a valid hostname. */
export function validateDomain(domain: string): void {
  if (!domain || !DOMAIN_RE.test(domain)) {
    throw new NginxError('SSL_DOMAIN', `Invalid domain: ${String(domain)}`);
  }
}

/** Throw a NginxError if a certificate path is not safe to embed in nginx config. */
export function validateCertPath(p: string): void {
  if (!p || !SAFE_PATH_RE.test(p) || p.includes('..')) {
    throw new NginxError('SSL_PATH', `Invalid certificate path: ${String(p)}`);
  }
}

function fragmentPathFor(domain: string): string {
  return path.join(CONF_DIR, `${SSL_FRAGMENT_PREFIX}${sanitizeDomain(domain)}${SSL_FRAGMENT_SUFFIX}`);
}
function fragmentBakPathFor(domain: string): string {
  return `${fragmentPathFor(domain)}.bak`;
}
function httpIncPath(): string {
  return path.join(CONF_DIR, HTTP_INC_NAME);
}
function httpIncBakPath(): string {
  return `${httpIncPath()}.bak`;
}

/** Build the per-domain 443 SSL server fragment (pure string). */
export function generateSslFragment(cert: SslCert): string {
  validateDomain(cert.domain);
  validateCertPath(cert.certPath);
  validateCertPath(cert.keyPath);
  return `# Auto-generated by qtechvending — DO NOT EDIT
server {
    listen 443 ssl;
    server_name ${cert.domain};

    ssl_certificate     ${cert.certPath};
    ssl_certificate_key ${cert.keyPath};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;

    # Reuse the main site proxy logic.
    location / {
        proxy_pass ${APP_UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
`;
}

/**
 * Build the http→https redirect include. Empty (comment only) when forceHttps
 * is off. Only emits redirects for the supplied enabled domains.
 */
export function generateHttpInc(forceHttps: boolean, enabledDomains: string[]): string {
  if (!forceHttps) {
    return '# Auto-generated by qtechvending — DO NOT EDIT (forceHttps disabled)\n';
  }
  const lines = enabledDomains
    .filter((d) => DOMAIN_RE.test(d))
    .map((d) => `if ($host = "${d}") { return 301 https://$host$request_uri; }`);
  return `# Auto-generated by qtechvending — DO NOT EDIT
${lines.join('\n')}
`;
}

interface ExecResult {
  ok: boolean;
  stderr: string;
}

/** Run `nginx <args>` capturing stderr; never throws. */
function runNginx(args: string[]): ExecResult {
  try {
    execFileSync(NGINX_BIN, args, { stdio: ['ignore', 'ignore', 'pipe'] });
    return { ok: true, stderr: '' };
  } catch (e: unknown) {
    const err = e as { stderr?: Buffer | string; message?: string };
    const stderr = err?.stderr ? String(err.stderr) : (err?.message ?? String(e));
    return { ok: false, stderr };
  }
}

function nginxTest(): ExecResult {
  return runNginx(['-t']);
}
function nginxReload(): ExecResult {
  return runNginx(['-s', 'reload']);
}

async function fileExists(p: string): Promise<boolean> {
  try {
    await fsp.access(p);
    return true;
  } catch {
    return false;
  }
}

/**
 * Idempotently ensure the main conf includes our SSL fragment glob (at EOF) and
 * the http redirect include (best-effort inside the first 80 server block).
 * Returns true on success (nginx -t passes); false if it cannot be applied —
 * the middleware 308 redirect is the safety net, so this degrades gracefully.
 */
export async function ensureMainConfIncludes(): Promise<boolean> {
  if (!(await fileExists(MAIN_CONF))) {
    console.warn('[nginx] main conf not found, skipping include injection:', MAIN_CONF);
    return false;
  }
  try {
    const original = await fsp.readFile(MAIN_CONF, 'utf8');
    let next = original;

    if (!next.includes(SSL_INCLUDE_DIRECTIVE)) {
      next = `${next.replace(/\s*$/, '')}\n\n# qtechvending: include generated SSL fragments\n${SSL_INCLUDE_DIRECTIVE}\n`;
    }
    if (!next.includes(HTTP_INCLUDE_DIRECTIVE)) {
      const injected = injectIntoFirstServer(next, `    ${HTTP_INCLUDE_DIRECTIVE}`);
      if (injected) {
        next = injected;
      } else {
        // Best-effort: if we cannot locate a server block, append at EOF so the
        // directive is at least present; the middleware handles the redirect.
        next = `${next.replace(/\s*$/, '')}\n${HTTP_INCLUDE_DIRECTIVE}\n`;
        console.warn('[nginx] could not locate an 80 server block; http include appended at EOF (best-effort).');
      }
    }

    if (next === original) return true; // already included — nothing to do

    // Backup + write + validate.
    await fsp.copyFile(MAIN_CONF, `${MAIN_CONF}.bak`);
    await fsp.writeFile(MAIN_CONF, next, 'utf8');
    const test = nginxTest();
    if (!test.ok) {
      await fsp.copyFile(`${MAIN_CONF}.bak`, MAIN_CONF); // rollback
      console.warn('[nginx] nginx -t failed after include injection; rolled back:', test.stderr);
      return false;
    }
    return true;
  } catch (e) {
    console.warn('[nginx] ensureMainConfIncludes error:', e);
    return false;
  }
}

/** Insert `line` just before the closing brace of the first `server { }` block. */
function injectIntoFirstServer(conf: string, line: string): string | null {
  const start = conf.indexOf('server');
  if (start === -1) return null;
  const open = conf.indexOf('{', start);
  if (open === -1) return null;
  let depth = 0;
  for (let i = open; i < conf.length; i++) {
    if (conf[i] === '{') depth++;
    else if (conf[i] === '}') {
      depth--;
      if (depth === 0) {
        const close = i;
        return `${conf.slice(0, close)}\n${line}\n${conf.slice(close)}`;
      }
    }
  }
  return null;
}

export interface NginxApplyResult {
  ok: boolean;
  appliedDomains?: number;
  error?: string;
}

/**
 * Apply the SSL configuration derived from a SiteSetting to live nginx.
 *
 * Workflow:
 *  1. backup currently-enabled fragments (.bak)
 *  2. write enabled fragments to their real paths
 *  3. delete fragments for disabled/removed domains
 *  4. write http.inc (forceHttps ? redirect : empty)
 *  5. `nginx -t` (NO reload yet)
 *  6. success → `nginx -s reload` → clear backups → { ok:true }
 *  7. failure → roll backups back over bad fragments, re-verify, NEVER reload
 */
export async function applyConfig(site: {
  forceHttps: boolean;
  sslCerts: SslCert[];
}): Promise<NginxApplyResult> {
  const certs = Array.isArray(site.sslCerts) ? site.sslCerts : [];
  const enabled = certs.filter((c) => c && c.enabled && c.domain);

  // Validate up front — a bad value reports an error and changes nothing.
  for (const c of enabled) {
    try {
      validateDomain(c.domain);
      validateCertPath(c.certPath);
      validateCertPath(c.keyPath);
    } catch (e) {
      const err = e as NginxError;
      return { ok: false, error: err.message };
    }
  }

  const enabledDomains = enabled.map((c) => c.domain);
  const dir = CONF_DIR;

  const backedUpDomains: string[] = []; // enabled domains whose .conf existed → backed up
  const createdDomains: string[] = []; // enabled domains whose .conf is newly created
  let httpIncExisted = false; // whether http.inc existed before this apply (for rollback)

  try {
    // 1. Backup enabled fragments (or note they are newly created).
    for (const c of enabled) {
      const fp = fragmentPathFor(c.domain);
      if (await fileExists(fp)) {
        await fsp.copyFile(fp, fragmentBakPathFor(c.domain));
        backedUpDomains.push(c.domain);
      } else {
        createdDomains.push(c.domain);
      }
    }

    // Backup http.inc if present.
    httpIncExisted = await fileExists(httpIncPath());
    if (httpIncExisted) await fsp.copyFile(httpIncPath(), httpIncBakPath());

    // 2. Ensure include directives exist in main conf (best-effort).
    await ensureMainConfIncludes();

    // 3. Write enabled fragments.
    await fsp.mkdir(dir, { recursive: true });
    for (const c of enabled) {
      await fsp.writeFile(fragmentPathFor(c.domain), generateSslFragment(c), 'utf8');
    }

    // 4. Delete fragments for domains not in the enabled set.
    const existing = (await fsp.readdir(dir)).filter(
      (f) => f.startsWith(SSL_FRAGMENT_PREFIX) && f.endsWith(SSL_FRAGMENT_SUFFIX)
    );
    for (const f of existing) {
      const domain = f.slice(SSL_FRAGMENT_PREFIX.length, f.length - SSL_FRAGMENT_SUFFIX.length);
      if (!enabledDomains.includes(domain)) {
        const fp = path.join(dir, f);
        await fsp.unlink(fp);
        if (await fileExists(`${fp}.bak`)) await fsp.unlink(`${fp}.bak`);
      }
    }

    // 5. Write http.inc.
    await fsp.writeFile(httpIncPath(), generateHttpInc(site.forceHttps, enabledDomains), 'utf8');

    // 6. Validate BEFORE reload.
    const test = nginxTest();
    if (!test.ok) {
      throw new NginxError('NGINX_T', test.stderr || 'nginx -t failed');
    }

    // 7. Reload only after a successful test.
    const reload = nginxReload();
    if (!reload.ok) {
      throw new NginxError('NGINX_RELOAD', reload.stderr || 'nginx -s reload failed');
    }

    // Success — clear backups.
    for (const d of backedUpDomains) {
      if (await fileExists(fragmentBakPathFor(d))) await fsp.unlink(fragmentBakPathFor(d));
    }
    if (httpIncExisted && (await fileExists(httpIncBakPath()))) await fsp.unlink(httpIncBakPath());

    return { ok: true, appliedDomains: enabled.length };
  } catch (e) {
    const err = e as NginxError;
    // Rollback: restore backed-up fragments, remove newly-created ones.
    for (const d of backedUpDomains) {
      const bak = fragmentBakPathFor(d);
      const fp = fragmentPathFor(d);
      if (await fileExists(bak)) await fsp.copyFile(bak, fp);
    }
    for (const d of createdDomains) {
      const fp = fragmentPathFor(d);
      if (await fileExists(fp)) await fsp.unlink(fp);
    }
    if (httpIncExisted) {
      const hbak = httpIncBakPath();
      if (await fileExists(hbak)) await fsp.copyFile(hbak, httpIncPath());
    } else if (await fileExists(httpIncPath())) {
      await fsp.unlink(httpIncPath());
    }
    // Re-verify the rollback leaves a valid config (best-effort signal).
    const reTest = nginxTest();
    const msg = err?.message
      ? reTest.ok
        ? err.message
        : `${err.message} (rollback applied; re-test still failing)`
      : 'nginx apply failed';
    return { ok: false, error: msg };
  }
}

/** Singleton-style bundle exported for route handlers / tests. */
export const nginxManager = {
  sanitizeDomain,
  validateDomain,
  validateCertPath,
  generateSslFragment,
  generateHttpInc,
  ensureMainConfIncludes,
  applyConfig,
};
